import { prisma } from "../src/config/database.js";

const users = [
  {
    fullName: "Viết Hùng",
    email: "viethung67895@gmail.com",
    phone: "0866142135",
    passwordHash: "$2b$10$sBXdNBaUWrGkiJ3FVvNExuSsxQ3nw9v/jtkASVfP2dVucTNAeKx82",
    role: "ADMIN",
    status: "ACTIVE",
  },
  {
    fullName: "Lê Lan",
    email: "23t1020297@husc.edu.vn",
    phone: "0866145135",
    passwordHash: "$2b$10$80MxMe0mT43KTsABpFH5F.loX6urqVmgm5OX3etztSEX9rNxk.9hy",
    role: "ADMIN",
    status: "ACTIVE",
  },
  {
    fullName: "ACC PHỤ",
    email: "23t1020197@husc.edu.vn",
    phone: "0912375601",
    passwordHash: "$2b$10$1VNs8DJvjncXtuqXTT9jiuBMC6pZa3XXz7RGkBj509GaQg.lNlxQO",
    role: "CUSTOMER",
    status: "ACTIVE",
  },
  {
    fullName: "user01",
    email: "user01@gmail.com",
    phone: "0912345601",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "ACTIVE",
  },
  {
    fullName: "user02",
    email: "user02@gmail.com",
    phone: "0912345602",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "ACTIVE",
  },
  {
    fullName: "user03",
    email: "user03@gmail.com",
    phone: "0912345603",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "ACTIVE",
  },
  {
    fullName: "user04",
    email: "user04@gmail.com",
    phone: "0912345604",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "ACTIVE",
  },
  {
    fullName: "user05",
    email: "user05@gmail.com",
    phone: "0912345605",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "ACTIVE",
  },
  {
    fullName: "user06",
    email: "user06@gmail.com",
    phone: "0912345606",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "ACTIVE",
  },
  {
    fullName: "user07",
    email: "user07@gmail.com",
    phone: "0912345607",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "ACTIVE",
  },
  {
    fullName: "user08",
    email: "user08@gmail.com",
    phone: "0912345608",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "ACTIVE",
  },
  {
    fullName: "user09",
    email: "user09@gmail.com",
    phone: "0912345609",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "ACTIVE",
  },
  {
    fullName: "user10",
    email: "user10@gmail.com",
    phone: "0912345610",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "ACTIVE",
  },
  {
    fullName: "user11",
    email: "user11@gmail.com",
    phone: "0912345611",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "ACTIVE",
  },
  {
    fullName: "user12",
    email: "user12@gmail.com",
    phone: "0912345612",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "ACTIVE",
  },
  {
    fullName: "user13",
    email: "user13@gmail.com",
    phone: "0912345613",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "ACTIVE",
  },
  {
    fullName: "user14",
    email: "user14@gmail.com",
    phone: "0912345614",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "ACTIVE",
  },
  {
    fullName: "user15",
    email: "user15@gmail.com",
    phone: "0912345615",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "ACTIVE",
  },
  {
    fullName: "user16",
    email: "user16@gmail.com",
    phone: "0912345616",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "INACTIVE",
  },
  {
    fullName: "user17",
    email: "user17@gmail.com",
    phone: "0912345617",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "INACTIVE",
  },
  {
    fullName: "user18",
    email: "user18@gmail.com",
    phone: "0912345618",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "BANNED",
  },
  {
    fullName: "user19",
    email: "user19@gmail.com",
    phone: "0912345619",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "BANNED",
  },
  {
    fullName: "user20",
    email: "user20@gmail.com",
    phone: "0912345620",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "CUSTOMER",
    status: "BANNED",
  },
];

await prisma.user.createMany({
    data: users,
});