import { prisma } from "../src/config/database.js";

const users = [
  {
    fullName: "user01",
    email: "user01@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user02",
    email: "user02@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user03",
    email: "user03@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user04",
    email: "user04@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user05",
    email: "user05@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user06",
    email: "user06@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user07",
    email: "user07@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user08",
    email: "user08@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user09",
    email: "user09@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user10",
    email: "user10@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user11",
    email: "user11@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user12",
    email: "user12@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user13",
    email: "user13@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user14",
    email: "user14@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user15",
    email: "user15@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user16",
    email: "user16@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user17",
    email: "user17@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user18",
    email: "user18@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user19",
    email: "user19@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
  {
    fullName: "user20",
    email: "user20@gmail.com",
    phone: "0000000000",
    passwordHash: "$2b$10$fakeHashedPassword",
    role: "user",
    status: "ACTIVE",
  },
];

await prisma.user.createMany({
    data: users,
});